### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by runemoennike** [kpoppel/homeassistant-novafos#10]
Hi

Suddenly yesterday the integration started complaining that it could no longer authenticate, and as such the readings cannot be updated :( Is anyone else experiencing this?

The log entry is as follows:

```
Logger: custom_components.novafos.coordinator
Source: custom_components/novafos/pynovafos/novafos.py:137
Integration: Novafos ([documentation](https://github.com/kpoppel/homeassistant-novafos), [issues](https://github.com/kpoppel/homeassistant-novafos/issues))
First occurred: 15:08:11 (250 occurrences)
Last logged: 20:35:36
Unexpected error fetching Novafos data: Code not retrieved correctly. Plugin will not continue login process. Check user/pass/supplierID

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/novafos/coordinator.py", line 41, in _async_update_data
    if not await self.hass.async_add_executor_job(self.api.authenticate):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/novafos/pynovafos/novafos.py", line 137, in authenticate
    raise LoginFailed('Code not retrieved correctly. Plugin will not continue login process.  Check user/pass/supplierID')
custom_components.novafos.pynovafos.novafos.LoginFailed: Code not retrieved correctly. Plugin will not continue login process.  Check user/pass/supplierID
```

What I've tried so far:
1. Restarted HA as well as the host device.
2. Uninstall and reinstall the integration.
3. Change the password at Novafos to make sure it was the right one.
4. Checked the supplier ID to make sure it hasn't changed.

All to no avail.

Now that the integration has been removed, it seems that it's no longer putting the failed login attempts in the log. Is there some other log settings I can change or code I can add to log these attempts?

The only log line I have for each attempt is:

`2022-09-15 20:41:33.231 DEBUG (SyncWorker_5) [custom_components.novafos.pynovafos.novafos] Got login form request_verification_token = (155 character token here)`

**Comment by kpoppel** [comment]
I have the same. Not blocked from logging in using the website, so I expect some change in the login procedure. Getting to the current one was not straight forward, so I hope any change made is not in the same league.

**Comment by kpoppel** [comment]
It seems a Google reCAPTCHA token was added to the login process. https://developers.google.com/recaptcha/docs/verify
If it is important I don't know, but it is different.  If the purpose is to hinder replay attacks it could be important for the login procedure.
 For now, disable the plugin - it will not work with this.

**Comment by runemoennike** [comment]
Argh! I looked around but I can't find any mention of an official API, neither from Novafos or the "Watts" app they refer to.

**Comment by kpoppel** [comment]
I have left a message on KMD easy-energy for their sales director:

> Som privat forbruger ønsker jeg at kunne hente mine data ud af easy-energy via software.  Lige nu ser det ud til at det kun er f.eks. vandværker eller andre professionelle aktører der har adgang til KMD APIet.  F.eks. har jeg som privat adgang til at generere et application-token til https://eloverblik.dk/welcome og den vej via deres API hente mine egne data ned via software.
>  Har eller vil KMD tilbyde denne mulighed?
> 
> For at give lidt baggrund, findes der et voksende community omkring selv-hostede automatiseringsløsninger i hjemmet, herunder HomeAssistant, hvor integrationer samler folks egne data.  Sådanne integrationer driver besparelser for de enkelte på tværs af alle forsyningspunkter.  Åbne APIer med f.eks. application-tokens gør det muligt at skrive disse integrationer.
> 
> Jeg håber der eksisterer noget, eller at KMD er åbne overfor at lade os hvis data I opbevarer tilgå disse på måder der giver mening i et samlet forsyningsoverblik hos den enkelte.

These are my data, and I really find it reasonable I can get access to them in ways I find meaningful.

**Comment by runemoennike** [comment]
Thank you.

I remember reading that initially there was no API access to the electricity consumption data either, but after a long and hard fight they agreed to open it up. Hopefully this won't be as difficult.

**Comment by kpoppel** [comment]
> Edit: I can't see a captcha on the website login. But you see it in the call from python?

As for this comment. I see this in the network traffic:
![image](https://user-images.githubusercontent.com/4174578/190626474-9db4ef4e-e1dc-4874-be34-0717a590c52f.png)
![image](https://user-images.githubusercontent.com/4174578/190626562-fa01fec9-97ed-4ec7-aa93-20071449e071.png) (new)
![image](https://user-images.githubusercontent.com/4174578/190626606-fbf29d00-cfdf-4879-828e-842c01b9a009.png) (new)
![image](https://user-images.githubusercontent.com/4174578/190626737-b63588d5-f968-47aa-a38e-b2294490adea.png) (new)
![image](https://user-images.githubusercontent.com/4174578/190626812-c549d5b8-77b3-4bf2-a61e-117a4bfd2eba.png) (new)
![image](https://user-images.githubusercontent.com/4174578/190626850-47979389-5da8-4624-94bf-cfa839da30bf.png)
![image](https://user-images.githubusercontent.com/4174578/190626881-27248a29-7507-4b39-8383-03ccc9eeab4d.png)
![image](https://user-images.githubusercontent.com/4174578/190626914-f7dd944e-8a69-4588-991a-6826c547e50b.png)
![image](https://user-images.githubusercontent.com/4174578/190626964-84148ab4-f4b4-4db9-9653-ea97aafc3072.png)

The (new) parts revolve around this reCAPTCHA.  Particularly the 2nd Login package submits formdata including email and password, and another hidden field I suspect is to avoid spoofed homepages (well done KMD), but now also two more fields "Input.CaptchaToken" and "g-recaptcha-response" I haven't seen before.

**Comment by runemoennike** [comment]
Yes I see that too, what a bother.

**Comment by runemoennike** [comment]
I wonder if there's a way to use the "Watts" app's backend instead. It would require sniffing the traffic from the phone or via an emulator... I might give it a shot one day.

**Comment by kpoppel** [comment]
I personally really dislike Google is now part of knowing I login to see my water data.

**Comment by kpoppel** [comment]
Watts.dk is currently only getting energy data from energinet.dk, and only customers on Aalborg Forsyning can follow their water usage, see https://watts.dk/funktioner/#alle

According to this page: https://www.kmd.dk/loesninger-og-services/loesninger/energi/kmd-easy-energy

SK Forsyning, Forsyning Helsingør, Frederikshavn Forsyning, Aarhus Kommune (AVA), Bornholms Energi og Forsyning, Fors, NK Forsyning, Silkeborg Forsyning, Arwos, Provas, Jysk Energi, Energistyrelsen, Svendborg Vand&Affald, Ørsted, Novafos (this integration), and Vestforsyning, and more use KMD easy-energy platform.

Having to walk through Watts to get to the API endpoint could be an option, just not a very direct one :-)

**Comment by runemoennike** [comment]
Hm I can follow my water usage via Watts, so I wonder how that works.

**Comment by kpoppel** [comment]
In any case I tried blocking the gstatic domain in the browser and attempt login.  It immediately responds with "Not sure you are human" and shows the login page again.  So I am pretty sure this is the core of this issue.
 Now to learn how to fix this... If it can be done in a browser it can be done in code.

**Comment by kpoppel** [comment]
I tried Watts app too now, indeed Novafos is the 2nd water supplier available. Could be interesting to know how they integrate.

**Comment by kpoppel** [comment]
I think the best I can do right now - as the very purpose of reCAPTCHA is to weed out automated access - is to allow pasting the Bearer token into Homeassistant, after which  the integration can update data freely.
This utilises the fact that logging into the service results in a 3600 second token from which the service can be used.  The token can be used by any service on the network.
The just pushed update is half-way there I think.  Data can still be imported into HA, but only after manually logging into the web-service and snipping the access token.

**Comment by PexJensen** [comment]
I can't get the integration to work, say's "Token update does not seem to have a valid length. Please check again. (This message is normal the first time the integration starts)"

My access_token is 1977 characters long? and not 1506 as you write in your documentation.

**Comment by kpoppel** [comment]
Ok

**Comment by kpoppel** [comment]
Okay, thanks for the update. I will set the limit to be at least 1500 characters then. It is just to keep possible paste errors out.

**Comment by kpoppel** [comment]
Release v3.0.1 allows longer token.

**Comment by PexJensen** [comment]
Works for me now.

Thanks.

**Comment by Sdahl1234** [comment]
I removed the integration and its not possible to add it again.

**Comment by runemoennike** [comment]
@kpoppel should this issue be kept open so people won't keep reporting it, until we have something from Novafos?

I wrote Novafos and the first reply hints they are unaware a captcha has been installed. I elaborated and now waiting for their reply again.

**Comment by kpoppel** [comment]
That is a very good idea.

**Comment by kpoppel** [comment]
I have left a note with Novafos kundeservice today as well (KMD sales earlier, but no response).  It is not great that a commercial product like the Watts app can gain problem-free API access to data, whereas we cannot.
The absolute non-sense is that as soon as the Bearer token is in hand, the integration works just like before.  We just need that token.

**Comment by runemoennike** [comment]
I'm guessing Watts pay for that access, but I agree it's ridiculous that they actively prevent free use of our own data.

**Comment by kpoppel** [comment]
I left a message with "identiy@kmd.dk" from coming across this: https://github.com/kmd-identity . It mentions OpenID Connect, which is how the login process is handled - disregarding the reCAPTCHA part.  If we're lucky they at least know of there is a path leading to authentication which does not require basically replaying the homepage in software.

Let's see.

**Comment by kpoppel** [comment]
I got an answer back on my request.  Basically the change from KMD side is to hinder abuse - which is fair enough.  Given increased hacking activity on Danish infrastructure it is the good old equation "convenience = 1/security", and securing our infrastructure can only be appreciated.

I was advised to acquire an optical eye to readout data.  This is a way of-course, and Kamstrup does have the hardware:

  * https://www.kamstrup.com/en-en/water-solutions/meters-devices/accessories/optical-readout-head/documents
  * https://www.kamstrup.com/en-en/water-solutions/meters-devices/accessories/pulse-adapter
  * Even a mbus<->wmbus adapter: https://www.kamstrup.com/en-en/water-solutions/meters-devices/accessories/wireless-mbus-dongle

I am pretty sure there are more 'open source' alternatives except for the likely proprietary changes made, or encryption of data.

I came across this:
https://www.ihc-user.dk/forum/forums/topic/6640-flowm%C3%A5ler-til-brugsvand/
and this product: https://www.relay.de/en/products/m-bus-accessories/optical-head/

After the advise to get the optical eye, I have requested some more information on this: any encryption keys needed mbus/wmbus, as the Kamstrup optical eye has a wired output for the pulse which then needs another running ESP-device or something to pickup these pulses and transmit them to Home Assistant (MQTT comes to mind) and connecting the pulse output to in interrupt to wake up the ESP.  but having a USB connected eye or simply reading the wireless signal with a wmbus dongle is just... easier.

**Comment by askpet** [comment]
> I got an answer back on my request. Basically the change from KMD side is to hinder abuse - which is fair enough. Given increased hacking activity on Danish infrastructure it is the good old equation "convenience = 1/security", and securing our infrastructure can only be appreciated.
> 
> I was advised to acquire an optical eye to readout data. This is a way of-course, and Kamstrup does have the hardware:
> 
> * https://www.kamstrup.com/en-en/water-solutions/meters-devices/accessories/optical-readout-head/documents
> * https://www.kamstrup.com/en-en/water-solutions/meters-devices/accessories/pulse-adapter
> * https://www.kamstrup.com/da-dk/varmeloesninger/intelligente-varmemaalere/accessories/common-usb-driver
> * Even a mbus<->wmbus adapter: https://www.kamstrup.com/en-en/water-solutions/meters-devices/accessories/wireless-mbus-dongle
> 
> I am pretty sure there are more 'open source' alternatives except for the likely proprietary changes made, or encryption of data.
> 
> I came across this: https://www.ihc-user.dk/forum/forums/topic/6640-flowm%C3%A5ler-til-brugsvand/ and this product: https://www.relay.de/en/products/m-bus-accessories/optical-head/
> 
> After the advice to get the optical eye, I have requested some more information on this: any encryption keys needed mbus/wmbus, as the Kamstrup optical eye has a wired output for the pulse which then needs another running ESP-device or something to pickup these pulses and transmit them to Home Assistant (MQTT comes to mind) and connecting the pulse output to in interrupt to wake up the ESP. but having a USB connected eye or simply reading the wireless signal with a wmbus dongle is just... easier.
> 
> Maybe this is for getting the encryption key directly from Kamstrup: https://www.kamstrup.com/en-en/-/media/files/my-kamstrup-guides/encryption-key/my-kamstrup-encryption-key-guide_en.pdf

WOW - This is really great work
Thanks!

**Comment by runemoennike** [comment]
Good work :) Am I understanding correctly that the meter sends out information regularly via wmbus already?

**Comment by kpoppel** [comment]
Yes this is what I have concluded.  In the answer from Novafos it is hinted that while I can attach an optical eye they reserve the right to take up that space for attaching an antenna if they cannot 'get the signal out of the building', as they write.
From this I conclude wmbus is used.  I have tried to register an account with Kamstrup to register my water meter, but the device is flagged as not open for retrieving the key for it that way.  I am awaiting answer from Novafos on this as they certainly have the access (it is their device after all) with reference to the fact that Radius will give out the key for the electricity meter on request.

**Comment by runemoennike** [comment]
Alright, very interesting.

I've heard a rumor that the meter uses the electricity meter (also from Kamstrup) to communicate long-distance. I guess that makes sense since I'm assuming the wmbus is short range only. I have a device in my electricity meter that reads out electricity usage -- it'd be interesting to see if there was a way to read out water usage as well that way, if the data is already going through the electricity meter.

**Comment by Sdahl1234** [comment]
Im using wmbusmeters (https://github.com/weetmuts/wmbusmeters) add-on to read my multical21 meter.
not much data but i get it live. Now i can blame who's using all the water
You need the encryption key for your meter

![image](https://user-images.githubusercontent.com/80645006/195105813-0ca4761d-5855-495a-8edf-4959eb8563d4.png)

**Comment by kpoppel** [comment]
@Sdahl1234 Very nice indeed.  Mine is an flowIQ 2200 Novafos branded.  What hardware did you buy and how did you get the keys?

**Comment by Sdahl1234** [comment]
I have a IMST 871a (im871a) and i just asked my watersupplier (Frederikshavn forsyning A/S) for the encryption key.

My next goal is to get the key for my heating supplier, because I get readings from my Mulical602 to, but i need the key

**Comment by kpoppel** [comment]
Great.  50€  at shop.imst.de which is probably much less than Kamstrup will charge for their device.

**Comment by Sdahl1234** [comment]
The add-on supports other dongles. I think you can flash old tv-tuner dongles, but i did'nt have the time to investigate a cheap solution. (too many IoT projects) 
I just picked IMST 871a because I was sure it supported reading both my water and heating meter AND i could get it in 3 days.

**Comment by runemoennike** [comment]
That'd be great. €76 is too much for me to justify spending on having this number on the dashboard, since I don't have any use for it other than curiosity.

Some day I'm going to look into how the Watts app fetches data as well. So far I managed to install it on an emulator, but I haven't had time to sniff data yet.

**Comment by kpoppel** [comment]
I tried installing Watts on the emulator.  It seems to use SSL pinning so decryption using MiTM (like fiddler) is kind of difficult.  Sources say decompile the APK and remove some safety settings - but that is also a little work.  but do let us know if you get around to do this :-)

**Comment by runemoennike** [comment]
I managed to sniff the traffic by setting up the android emulator to use Fiddler as a proxy, as described here: https://docs.telerik.com/fiddler-everywhere/traffic/configure-android

I can see the login traffic, but the app throws an error on the reply from the server to the login request. Maybe it's due to the custom certificate. I'm trying to rebuild the apk to accept user certificates as described here https://book.hacktricks.xyz/mobile-pentesting/android-app-pentesting/make-apk-accept-ca-certificate .

**Comment by kpoppel** [comment]
It is possible using selenium test tool to automate the login.  It needs either Firefox or Chrom(e/ium) to be installed on the system, but I have been retrieving tokens all day long, and verified the retrieved token does fetch data from the datahub by inserting it using the configuration method I made recently..

**Comment by runemoennike** [comment]
Oh that's interesting. Does it require a windowing environment or do you think it could run headless, so we can put it in an add-on perhaps?

**Comment by kpoppel** [comment]
Well getting it into Home Assistant in a HASSIO setting is less than easy because selenium-wire requires gcc to install, and that is not present on HASSIO.
So I am looking into this:
* pull docker container selenium/standalone-firefox <- this one uses xrfb and exposes the screen through VNC, so that's cool.
* make another container with the necessary python-stuff in it and a small webserver which in turn dos all the selenium stuff on the other container.  This service would then return the token back to the integration and the rest is as always.

I don't know how to make an add-on, but people running this on RPis would be out of the question, both because the selenium container sucks up 1 GB space and a lot of RAM.
For now I am just looking at making a docker-compose file to prepare this on another VM somewhere.  Caveats are that I have no idea of programming en´ven a simple Python web service, so need to learn that too.
  I just need one single endpoint http://<dockerhost>:8123/tokenapi which returns a token

Btw. the captcha did come back with a "we cannot figure out if you are human" once, so this is also not a sure fire method.  I hope though that polling once per 24 hours with some differences in polling time of day and time from filling out the form and "pressing Enter" would be enough to not trigger the robot-mode.  Otherwise things will fail, I can dump a screenshot of what went wrong, and maybe a human login once in a while is enough.  Let's see.

**Comment by runemoennike** [comment]
I think an add-on is just a docker container, but if it needs multiple docker containers idk if it's possible. The 1GB space wouldn't be an issue for people with an SSD on the RPi, but the ram might indeed be.

I've used Tornado to expose endpoints as a webserver with python and it was pretty simple iirc. I don't know if it's still the flavour of the day or if something better has come out since.

I was wondering if the captcha "learns" to recognise a bot if it does the same movement every time, so some variation might be smart as you say, maybe if "jiggle" the mouse a bit or something.

**Comment by kpoppel** [comment]
I have settled for building on top of the selenium/standalone-chrome:4.5.0 container.  It turned out that was the easiest thing to do - basically adding the Flask Python code and getting supervisord to start it.  So this is a single container with everything in it now.  I still need to learn how to pass username and password in a GET, but it reacts nicely to hardcoded values now using curl on the endpoint.  Basically forwarding the oidc token like we were used to.

So next step is to stitch this into HomeAssistant and pass the credentials properly.

**Comment by runemoennike** [comment]
Awesome!

Not sure if it's possible in this case, but normally username/passwords are passed via POST requests to avoid logging them to request logs, for obvious security reasons. Might not be so relevant here, if it all runs on a local network, but just thought I'd mention it since I have some experience in that field hehe.

**Comment by kpoppel** [comment]
Good point. I'll make it a Post. Too much to learn due to this 😁

**Comment by kpoppel** [comment]
I have committed what I have in this branch: [v4-selenium](https://github.com/kpoppel/homeassistant-novafos/tree/v4-selenium)
It is a little rough around the edges, with required changes in a few files, but now it is here.  Refer to the README.md for details.

**Comment by runemoennike** [comment]
Great work!

If it's not too much trouble, could you check how much RAM the docker container uses? I'm wondering if my NAS is able to run it at all.

**Comment by kpoppel** [comment]
`docker stats --no-stream` says:
```
CONTAINER ID   NAME                              CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
f569b9e5c4c7   selenium-pyapi                    1.27%     696.6MiB / 7.737GiB   8.79%     122MB / 363MB     211MB / 5.77GB    46
```

So it is quite hungry this one.  I suppose the effect of running a full X-server and a Chrome browser makes it so unfortunately.
But it works and has fetched data for me daily since I deployed the container.

**Comment by runemoennike** [comment]
Cool, thanks :)

I briefly read about running Chrome headless via Selenium, maybe it can
even run without an X-server then. I haven't had time to experiment with it
yet.

**Comment by kpoppel** [comment]
A quick search says screenshot may be possible: https://code-maven.com/slides/python/selenium-headless-screenshot, which is a requirement in case this feature is caught up in the machine.  This tutorial might be something to try: https://linuxhint.com/chrome_selenium_headless_running/

It could be a pretty cool optimisation for resource use to let go of the UI if possible.  Maybe also the dependency on the selenium-docker could be scaled down to just installing Chrome, chromedriver, python3 and the appropriate selenium packages.

**Comment by achton** [comment]
Are any of you familiar with [Cypress](https://www.cypress.io)? I believe it solves some of the same problems as Selenium, and also runs in a (headless) browser, but being more modern it may have a more performant approach. Just a thought.

Cypress has [readily made Docker images](https://docs.cypress.io/examples/examples/docker#Images) and can also be set up to [measure its own resource usage](https://docs.cypress.io/guides/references/troubleshooting#Log-memory-and-CPU-usage) from inside the container.


(Also: excellent work and findings in this issue 👏🏻 )

**Comment by kpoppel** [comment]
I haven't seen Cypress before.  I am unsure if it is 'just' another way to drive Chrome, and that it is Chrome which make up the bulk of the memory footprint.

**Comment by kpoppel** [comment]
One could only hope....  I got a mail from the team leader for customer support with a notice that he sent on my request for API access to Novafos metering data to their project department.
 For now, the most reliable path it seems is to manually copy in the token in Home Assistant.

Keep complaining to Novafos (and any other KMD Easy-energy customers) - only in numbers will this get attention.

**Comment by runemoennike** [comment]
Just a small update: I was playing around with getting the docker container running directly on the RPi4, which seems to work. I've enabled the headless mode, but the integration itself doesn't seem able to authenticate through it, throwing the error "Failed to retrieve bearer token (no JSON returned)".

I don't have a way to connect to the docker image since it's running on the HA RPi, and going to the "web ui" for the add-on just shows "internal server error". I couldn't see anything in the add-on log for either error.

I'll play around more another day :)

**Comment by kpoppel** [comment]
I have a few issues with this at the moment.  One is that a new header is required now.  This is being fixed right now.

As for the docker venture here it is something which is trying to fight Google's AI and clever developers figuring out if a browser is machine or human controlled.  Let's just say this is a battle I cannot win by any length.
Last time I checked on my docker image status the browser would consistently display blank pages and hence never get anything to login with.  some suggests randomly choosing a browser meaning more stuff in the container, and various things with full screen UI, mouse movement simulators and what not.  In the end KMD are the ones to be poked from as many people as possible to allow customers to generate an access token to allow API accesses without requiring a human at the keyboard.

If you find a way to do this login, please share it. I have spent a lot of hours and nights on this just to get to a solution which worked a month or two :-)
Also do make a merge request to this repository so that more can get the benefits.

*rant on*
It is simply ridiculous that this is not possible when we can get heating data, electricity data, car data (for EVs anyway), and so on using 3rd party software like this one through API access tokens.  For all I care they can revoke the tokens every month, but let us have the darned token.
*rant off*

**Comment by kblin** [comment]
I guess I'll be sending an email to KMD as well. They clearly have a setup for Watts, it's silly they don't offer that for other tools.

**Comment by kpoppel** [comment]
I have made this Chrome add-on to semi-automate the process now: https://github.com/kpoppel/homeassistant-novafos-chrome-addon

It relies on a person to login, but from there automatically extracts the authentication token and can send it to your Home Assistant.  the latest release v.4.3.x has this feature. (And 5.x-beta too of course).  At least it now takes 10 seconds to update data whenever it is convenient.  v5.x uses the statistics history in Home Assistant, so no more heaps of data in the attributes.

**Comment by doeleman** [comment]
I've added the Chrome extension. I can see that it extracts the token, but when I click "Send Token to Home Assistant", I first get a "Token sent to Home Assistant" for a millisecond, followed by a "Something went wrong: Unexpected non-whitespace character after JSON at position 3 (line 1 column 4).

Any ideas about what I need to change?

**Comment by kpoppel** [comment]
Courageous, and thanks for trying it out :-)  If you use the version with this repository, you may want to switch over to the (currently identical) version in the repository now dedicated for the extension:

So... Many things can go wrong, but first of all make sure your Home Assistant instance is accessible over https.  You can try to send the service call from your commandline using curl, like so:
```
curl -X POST \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Authorization: Bearer $ha_token" \
  -d "{\"access_token\": \"$access_token\"}" \
  "$ha_url/api/services/novafos/update_token"
```
exchange the $variables with your local info.  You need the Home Assistant long lived access token, bearer token from Chrome and the https:// url for your home assistant instance.  This is basically the core of the Chrome extension :-)

In Home assistant, make sure to make the changes in configuration.yaml for CORS.

**Comment by doeleman** [comment]
Thanks - got it to work! I think it was an error with the HA token.

Anoter questions: Is it possible to use the data for the Energy dashboard? Which sensor should I use?

**Comment by kpoppel** [comment]
Yes,  You plug in the "sensor.novafos_water_statistics" in the energy dashboard.  It will complain that the entity is unavailable because it has always unknown state, but we realise this is true as data is never real-time, and ignore it :-)  The extended day/week/month/year sensors are just for the statistics-graph cards.
  So with the hourly statistics you will get the right data on the right days:

![Image](https://github.com/user-attachments/assets/eca76e3c-d092-4b21-afea-c0a98fa8c1da)
