### ISSUE TITLE
def _get_hour_data

### ISSUE THREAD

**Issue by MBURKU** [kpoppel/homeassistant-novafos#17]
Hi

I get the error below. Is it something you have seen before?

Logger: custom_components.novafos.coordinator
Kilde: helpers/update_coordinator.py:382
integration: Novafos (dokumentation, problemer)

2024-11-14 10:39:56.209 DEBUG (SyncWorker_4) [custom_components.novafos.pynovafos.novafos] Retrieved data from API: [{'type': 'heating', 'Data': [{'DateFrom': '2024-11-13T00:00:00', 'DateTo': '2024-11-13T00:59:59', 'Value': 0.001}], 'Total': {'Value': 0.001, 'DateFrom': '2024-11-13T00:00:00+01:00', 'DateTo': '2024-11-13T23:59:59+01:00'}, 'Average': {'Value': 0.001, 'DateFrom': '2024-11-13T00:00:00', 'DateTo': '2024-11-13T00:59:59'}, 'Maximum': {'Value': 0.001, 'DateFrom': '2024-11-13T00:00:00', 'DateTo': '2024-11-13T00:59:59'}, 'Minimum': {'Value': 0.001, 'DateFrom': '2024-11-13T00:00:00', 'DateTo': '2024-11-13T00:59:59'}, 'LastValidDate': '2024-11-13T00:59:59'}, {'type': 'water', 'Data': [{'DateFrom': '2024-11-13T00:00:00', 'DateTo': '2024-11-13T00:59:59', 'Value': 0.0}], 'Total': {'Value': 0.0, 'DateFrom': '2024-11-13T00:00:00+01:00', 'DateTo': '2024-11-13T23:59:59+01:00'}, 'Average': {'Value': 0.0, 'DateFrom': '2024-11-13T00:00:00', 'DateTo': '2024-11-13T00:59:59'}, 'Maximum': {'Value': 0.0, 'DateFrom': '2024-11-13T00:00:00', 'DateTo': '2024-11-13T00:59:59'}, 'Minimum': {'Value': 0.0, 'DateFrom': '2024-11-13T00:00:00', 'DateTo': '2024-11-13T00:59:59'}, 'LastValidDate': '2024-11-13T00:59:59'}]
2024-11-14 10:39:56.210 ERROR (MainThread) [custom_components.novafos.coordinator] Unexpected error fetching Novafos data

Unexpected error fetching Novafos data
Traceback (most recent call last):
  File "/config/custom_components/novafos/coordinator.py", line 76, in _async_update_data
    data = await self.hass.async_add_executor_job(self.api.get_latest)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/novafos/pynovafos/novafos.py", line 646, in get_latest
    self._get_hour_data(days_back=1)
  File "/config/custom_components/novafos/pynovafos/novafos.py", line 548, in _get_hour_data
    self._meter_data[type]['hour']['Data'] = self._meter_data[type]['hour']['Data'] + series['Data']
                                             ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'hour'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/novafos/coordinator.py", line 78, in _async_update_data
    raise ConfigEntryNotReady from error
homeassistant.exceptions.ConfigEntryNotReady: 'hour'

**Comment by kpoppel** [comment]
Okay, this looks like the data is 'heating'.  This is a new data type for me as I personally only get water data from them.
If you can send me full debugging information (check the README.md file), I can give it a try to 
1) first safely ignore the data
2) make proper sensors extracting the new dataset
